# Generated by Django 4.2.5 on 2023-09-05 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Songer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_music', models.CharField(max_length=40)),
                ('number', models.IntegerField()),
                ('alb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='api.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.songs'),
        ),
        migrations.AddField(
            model_name='album',
            name='songer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.songer'),
        ),
    ]
