# Generated by Django 4.2.5 on 2023-09-05 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_album_song_alter_album_songer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='song',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='alb',
        ),
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songs',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.album'),
            preserve_default=False,
        ),
    ]
